### ISSUE TITLE
Access other rels from the homepage

### ISSUE THREAD

**Issue by pstuifzand** [grantcodes/micropub#11]
It would be useful to be able to access the other rels from the users homepage. For example: the "microsub" rel. Otherwise an user of the library would need to get the page again.

**Comment by grantcodes** [comment]
Agreed, I think though it would be best to separate rel scraping part into a separate library that can be used in multiple projects.

I already made a [function to do this for together](https://github.com/cleverdevil/together/blob/master/server/lib/rel-scraper.js) although no guarantees on the robustness of this.

@martymcguire already did something along those lines, separating out the indieauth component from this library into https://www.npmjs.com/package/indieauth-authentication

So maybe there should be 3 separate parts? The rel scraper, the indieauth part and the micropub part. Just not sure of the best way of going about it. I wonder if there is a case to be made for creating an indieweb org on npm now and having them live there

**Comment by grantcodes** [comment]
Closing as I created https://github.com/grantcodes/rel-parser
