### ISSUE TITLE
"The me values did not match" on commentpara.de

### ISSUE THREAD

**Issue by cweiske** [grantcodes/micropub#13]
commentpara.de supports multiple users on the same domain.
When logging into commentpara.de with indieauth, people are expected to put in "https://commentpara.de/" as "me" URL. The IndieAuth process happens then, and at the end a user-specific me URL will be returned.

Input URL: `https://commentpara.de/`
Final URL: `https://commentpara.de/user/3.htm`

micropub-helper does not support this; it only says "The me values did not match".

----

The specification [says about this](https://indieauth.spec.indieweb.org/#access-token-response-p-2):

> The resulting profile URL MAY be different from what the user initially entered, but MUST be on the same domain.

(Related to https://github.com/keithjgrant/omnibear/issues/82)

**Comment by grantcodes** [comment]
Ah ok, that shouldn't be too hard to update. It will just need to parse the
urls for the hostname

**Comment by grantcodes** [comment]
Oh thanks for helping! Those changes are in v1.5.3
